apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: images-demo
  labels:
    app: images-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images-demo
  template:
    metadata:
      labels:
        app: images-demo
    spec:
      containers:
      - name: images-demo-ctr
        image: ubuntu:14.04
