apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: monitor-demo
  labels:
    app: monitor-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-demo
  template:
    metadata:
      labels:
        app: monitor-demo
    spec:
      containers:
      - name: monitor-demo-ctr
        image: nginx:latest
