apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubecon-demo
  labels:
    app: kubecon-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecon-demo
  template:
    metadata:
      labels:
        app: kubecon-demo
    spec:
      serviceAccountName: kubecon
      containers:
      - name: memory-demo-ctr
        image: alena1108/kubecon:v0.6.1
        imagePullPolisy: Always
